// @vitest-environment node
import {randomUUID} from "node:crypto";
import {PrismaClient,Role} from "@prisma/client";
import {beforeAll,afterAll,describe,expect,it,vi} from "vitest";
const m=vi.hoisted(()=>({client:null as any}));vi.mock("@/lib/db",()=>({db:new Proxy({},{get(_t,key){const value=m.client[key];return typeof value==="function"?value.bind(m.client):value;}})}));
import {recordBagEvent,listBagCustody} from "@/lib/laundry/bag-custody";
import {readTurnoverProfit,saveTurnoverCosts} from "@/lib/finance/turnover-profit";
const url=process.env.SNEEK_TEST_DATABASE_URL;
const [adminId,cleanerId,laundryId,strangerId,clientUser,clientId,propertyId,jobId,taskId,invoiceId]=Array.from({length:10},()=>randomUUID());
const admin={id:adminId,role:Role.ADMIN},cleaner={id:cleanerId,role:Role.CLEANER},laundry={id:laundryId,role:Role.LAUNDRY},stranger={id:strangerId,role:Role.CLEANER},client={id:clientUser,role:Role.CLIENT};
const input=()=>({requestId:randomUUID(),taskId,bagId:`bag-${taskId}`,expectedVersion:0,status:"REGISTERED",observedAt:new Date(Date.now()-1000).toISOString(),location:"Fixture cupboard",contents:null,itemCount:null,note:"Label observed; contents not checked"});
describe.skipIf(!url)("bag custody and turnover finance integration",()=>{
 beforeAll(async()=>{if(new URL(url!).hostname!=="127.0.0.1"||new URL(url!).port!=="55439")throw Error("Dedicated fixtures required");m.client=new PrismaClient({datasources:{db:{url}}});await m.client.user.createMany({data:[admin,cleaner,laundry,stranger,client].map(user=>({id:user.id,role:user.role,email:`${user.id}@example.invalid`}))});await m.client.client.create({data:{id:clientId,name:"Fixture"}});await m.client.property.create({data:{id:propertyId,clientId,name:"Fixture",address:"Fixture",suburb:"Fixture",accessInfo:{laundryTeamUserIds:[laundryId]}}});await m.client.job.create({data:{id:jobId,jobNumber:jobId,propertyId,jobType:"AIRBNB_TURNOVER",fixedPrice:120,status:"ASSIGNED",scheduledDate:new Date(),assignments:{create:{userId:cleanerId,responseStatus:"ACCEPTED"}}}});await m.client.laundryTask.create({data:{id:taskId,jobId,propertyId,pickupDate:new Date(),dropoffDate:new Date(Date.now()+3*86400000)}});await m.client.clientInvoice.create({data:{id:invoiceId,clientId,invoiceNumber:invoiceId,status:"SENT",totalAmount:110,subtotal:100,gstAmount:10,lines:{create:{jobId,description:"Turnover",quantity:1,unitPrice:100,lineTotal:100,category:"CLEANING"}}}});});
 afterAll(async()=>{await m.client.appSetting.deleteMany({where:{OR:[{key:`turnover_cost_review_v1:${jobId}`},{key:{startsWith:"linen_bag_v1:"},value:{path:["propertyId"],equals:propertyId}}]}});await m.client.auditLog.deleteMany({where:{userId:{in:[adminId,cleanerId,laundryId]}}});await m.client.clientInvoice.delete({where:{id:invoiceId}});await m.client.laundryTask.delete({where:{id:taskId}});await m.client.jobAssignment.deleteMany({where:{jobId}});await m.client.job.delete({where:{id:jobId}});await m.client.property.delete({where:{id:propertyId}});await m.client.client.delete({where:{id:clientId}});await m.client.user.deleteMany({where:{id:{in:[adminId,cleanerId,laundryId,strangerId,clientUser]}}});await m.client.$disconnect();});
 it("applies laundry-team scope before the recent-run limit", async () => {
  const hiddenProperty = randomUUID();
  const hiddenJobs = Array.from({length: 101}, () => randomUUID());
  await m.client.property.create({data: {id: hiddenProperty, clientId, name: "Other team", address: "Fixture", suburb: "Fixture", accessInfo: {laundryTeamUserIds: [adminId]}}});
  try {
   await m.client.job.createMany({data: hiddenJobs.map(id => ({id, jobNumber: id, propertyId: hiddenProperty, jobType: "AIRBNB_TURNOVER", scheduledDate: new Date()}))});
   await m.client.laundryTask.createMany({data: hiddenJobs.map(id => ({jobId: id, propertyId: hiddenProperty, pickupDate: new Date(Date.now() + 86400000), dropoffDate: new Date(Date.now() + 172800000)}))});
   const visible = await listBagCustody(laundry);
   expect(visible.tasks.some(row => row.id === taskId)).toBe(true);
   expect(visible.tasks.some(row => hiddenJobs.includes(row.job))).toBe(false);
  } finally {
   await m.client.laundryTask.deleteMany({where: {propertyId: hiddenProperty}});
   await m.client.job.deleteMany({where: {propertyId: hiddenProperty}});
   await m.client.property.delete({where: {id: hiddenProperty}});
  }
 });
 it("keeps individual observations, unknown counts and legacy laundry state separate; retries append once",async()=>{const request=input();const [a,b]=await Promise.all([recordBagEvent(cleaner,request),recordBagEvent(cleaner,request)]);expect(a.version).toBe(1);expect(b.version).toBe(1);expect(a.itemCount).toBeNull();const picked=await recordBagEvent(laundry,{...request,requestId:randomUUID(),expectedVersion:1,status:"PICKED_UP"});await recordBagEvent(laundry,{...request,requestId:randomUUID(),expectedVersion:picked.version,status:"RETURNED",location:"Returned to property"});const result=await listBagCustody(cleaner,taskId);expect(result.events).toHaveLength(3);expect(result.events.map(row=>row.status)).toEqual(["REGISTERED","PICKED_UP","RETURNED"]);const legacy=await m.client.laundryTask.findUnique({where:{id:taskId}});expect(legacy.status).toBe("PENDING");expect(legacy.pickedUpAt).toBeNull();expect(legacy.droppedAt).toBeNull();await expect(recordBagEvent(cleaner,{...request,note:"Changed retry"})).rejects.toThrow("CONFLICT");});
 it("enforces current assignment, laundry-team and client privacy",async()=>{await expect(listBagCustody(stranger,taskId)).rejects.toThrow("FORBIDDEN");await expect(listBagCustody(client,taskId)).rejects.toThrow("FORBIDDEN");await expect(recordBagEvent(cleaner,{...input(),status:"PICKED_UP"})).rejects.toThrow("Only the laundry team");await m.client.property.update({where:{id:propertyId},data:{accessInfo:{laundryTeamUserIds:[adminId]}}});await expect(listBagCustody(laundry,taskId)).rejects.toThrow("FORBIDDEN");await m.client.jobAssignment.updateMany({where:{jobId},data:{removedAt:new Date()}});await expect(listBagCustody(cleaner,taskId)).rejects.toThrow("FORBIDDEN");});
 it("keeps cash and missing costs unknown, and audited cost review never alters prices, pay or invoices",async()=>{expect((await readTurnoverProfit(admin,jobId)).detail).toMatchObject({profit:null,totalCost:null,revenue:{invoiced:100,cash:null},agreedPriceEstimate:120});const costs={CLEANER:{amount:40,reference:"Reviewed supplier bill"},LAUNDRY:{amount:0,reference:"No laundry charge for fixture"},SUPPLIES:{amount:0,reference:"No supplied consumables for fixture"},OTHER:{amount:0,reference:"No other attributable costs for fixture"}};await saveTurnoverCosts(admin,{jobId,expectedVersion:0,confirmed:true,costs});expect((await readTurnoverProfit(admin,jobId)).detail).toMatchObject({profit:60,totalCost:40,revenue:{cash:null}});await expect(saveTurnoverCosts(admin,{jobId,expectedVersion:0,confirmed:true,costs})).rejects.toThrow("CONFLICT");expect((await m.client.job.findUnique({where:{id:jobId}})).fixedPrice).toBe(120);expect((await m.client.clientInvoice.findUnique({where:{id:invoiceId}})).status).toBe("SENT");for(const user of [cleaner,laundry,stranger,client]){await expect(readTurnoverProfit(user,jobId)).rejects.toThrow("FORBIDDEN");await expect(saveTurnoverCosts(user,{jobId,expectedVersion:1,confirmed:true,costs})).rejects.toThrow("FORBIDDEN");}});
});
