ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'PAUSED';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'WAITING_CONTINUATION_APPROVAL';
ALTER TYPE "LaundryStatus" ADD VALUE IF NOT EXISTS 'SKIPPED_PICKUP';
