// @vitest-environment node
import {beforeEach,expect,it,vi} from "vitest";
const m=vi.hoisted(()=>({role:vi.fn(),job:vi.fn(),pick:vi.fn(),guard:vi.fn(),notice:vi.fn(),push:vi.fn(),audit:vi.fn()}));
vi.mock("@/lib/auth/session",()=>({requireRole:m.role}));vi.mock("@/lib/qa/pickup",()=>({pickUpQaAssignment:m.pick}));vi.mock("@/lib/qa/self-review",()=>({assertNotSelfInspection:m.guard}));vi.mock("@/lib/notifications/web-push",()=>({sendWebPushToUser:m.push}));vi.mock("@/lib/logger",()=>({logger:{error:vi.fn()}}));vi.mock("@/lib/db",()=>({db:{job:{findUnique:m.job},notification:{createMany:m.notice},auditLog:{create:m.audit}}}));
import {POST} from "@/app/api/qa/jobs/[id]/pickup/route";
const run=()=>POST(new Request("http://localhost",{method:"POST",body:JSON.stringify({reason:"Client released room early"})}),{params:{id:"j"}});
beforeEach(()=>{vi.resetAllMocks();m.role.mockResolvedValue({user:{id:"qa"}});m.job.mockResolvedValue({id:"j",status:"IN_PROGRESS",property:{name:"Home"},formSubmissions:[],assignments:[{userId:"cleaner"},{userId:"cleaner"}]});m.pick.mockResolvedValue({assignment:{id:"a",status:"IN_PROGRESS"},unchanged:false});});
it("early pickup records one jobs-category inbox nudge per cleaner",async()=>{expect((await run()).status).toBe(200);expect(m.pick).toHaveBeenCalledWith({jobId:"j",userId:"qa",earlyStartReason:"Client released room early"});expect(m.notice).toHaveBeenCalledWith({data:[expect.objectContaining({userId:"cleaner",externalId:expect.stringContaining("jobs"),status:"SENT"})]});expect(m.push).toHaveBeenCalledTimes(1);expect(m.audit).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({after:expect.objectContaining({startedBeforeSubmission:true})})}));});
it("repeat pickup returns saved assignment without another nudge or audit",async()=>{m.pick.mockResolvedValue({assignment:{id:"a",status:"IN_PROGRESS"},unchanged:true});const response=await run();expect(response.status).toBe(200);expect(await response.json()).toMatchObject({id:"a"});expect(m.notice).not.toHaveBeenCalled();expect(m.push).not.toHaveBeenCalled();expect(m.audit).not.toHaveBeenCalled();});
it("ownership failure from transactional pickup cannot send early-start nudge",async()=>{m.pick.mockRejectedValue(new Error("FORBIDDEN"));expect((await run()).status).toBe(403);expect(m.notice).not.toHaveBeenCalled();expect(m.audit).not.toHaveBeenCalled();});
