// @vitest-environment node
import { beforeEach, expect, it, vi } from "vitest";
const m = vi.hoisted(() => ({ find: vi.fn(), update: vi.fn(), upsert: vi.fn(), submission: vi.fn(), settings: vi.fn(), compare: vi.fn(), image: vi.fn() }));
vi.mock("@/lib/db", () => ({ db: { aiPhotoReview: { findMany: m.find, updateMany: m.update, upsert: m.upsert }, formSubmission: { findUnique: m.submission } } }));
vi.mock("@/lib/ai/vision-settings", () => ({ getVisionSettings: m.settings }));
vi.mock("@/lib/ai/vision", () => ({ compareReferencePhotos: m.compare }));
vi.mock("@/lib/ai/images", () => ({ loadVisionImage: m.image }));
import { enqueuePhotoReview, processPhotoReviewQueue, photoSourceFingerprint } from "@/lib/ai/photo-review";
import { DEFAULT_VISION_SETTINGS } from "@/lib/ai/vision-settings-schema";
import { parsePhotoReviewResult, proposedPhotoDeduction } from "@/lib/ai/photo-review-policy";
let submission: any; let candidate: any; const settings = { ...DEFAULT_VISION_SETTINGS, comparisonEnabled: true, batchSize: 1, model: "snapshot-model" };
beforeEach(() => {
 vi.resetAllMocks(); submission = { id: "submission", laundryReady: true, data: { __templateSchema: { sections: [{ fields: [{ id: "bath", type: "photo", label: "Bathroom", references: [{ kind: "image", storageKey: "form-references/owner/bath.jpg" }] }] }] } }, job: { property: { bedrooms: 2 } }, media: [1,2].map(n => ({ id: `photo${n}`, fieldId: "bath", mediaType: "PHOTO", s3Key: `forms/job/photo${n}` })) };
 candidate = { id: "review", submissionId: submission.id, settings, result: null, updatedAt: new Date(), sourceFingerprint: null };
 m.find.mockImplementation(async () => [candidate]); m.submission.mockImplementation(async () => submission); m.settings.mockResolvedValue({ ...settings, model: "current-model" }); m.update.mockResolvedValue({ count: 1 }); m.image.mockResolvedValue({ id: "photo", data: "eA==", mediaType: "image/jpeg" }); m.compare.mockResolvedValue({ assessment: "pass", summary: "Clear", confidence: .95, issues: [] });
});
it("enqueues only when enabled without calling the provider or changing a score", async () => { expect(await enqueuePhotoReview("submission")).toBe(true); expect(m.upsert).toHaveBeenCalledWith(expect.objectContaining({ update: {} })); expect(m.compare).not.toHaveBeenCalled(); m.settings.mockResolvedValue({ comparisonEnabled: false }); expect(await enqueuePhotoReview("next")).toBe(false); });
it("commits one durable chunk with snapshot model and resumes only remaining photos", async () => {
 expect(await processPhotoReviewQueue()).toEqual({ processed: 1 });
 const claim = m.update.mock.calls[1][0]; expect(claim.where).toMatchObject({ updatedAt: candidate.updatedAt, attempts: { lt: 3 } });
 const first = m.update.mock.calls[2][0]; expect(first.data.status).toBe("PENDING"); expect(first.data.result.observations).toHaveLength(1); expect(m.compare.mock.calls[0][1].model).toBe("snapshot-model");
 candidate = { ...candidate, result: first.data.result, sourceFingerprint: first.data.sourceFingerprint }; m.update.mockClear(); m.compare.mockClear();
 await processPhotoReviewQueue(); expect(m.update.mock.calls[2][0].data.status).toBe("READY"); expect(m.compare).toHaveBeenCalledTimes(1); expect(m.image.mock.calls.at(-1)?.[0]).toBe("forms/job/photo2");
});
it("losing the claim never calls provider; losing final lease never counts committed work", async () => { m.update.mockResolvedValueOnce({ count: 0 }).mockResolvedValueOnce({ count: 0 }); expect(await processPhotoReviewQueue()).toEqual({ processed: 0 }); expect(m.compare).not.toHaveBeenCalled(); m.update.mockResolvedValueOnce({ count: 1 }).mockResolvedValueOnce({ count: 1 }).mockResolvedValueOnce({ count: 0 }); expect(await processPhotoReviewQueue()).toEqual({ processed: 0 }); });
it("disabling mid-batch stops further photos and fails without pass result", async () => { candidate.settings.batchSize = 2; m.settings.mockResolvedValueOnce({ ...settings, batchSize: 2 }).mockResolvedValueOnce(settings).mockResolvedValueOnce({ ...settings, comparisonEnabled: false }); await processPhotoReviewQueue(); expect(m.compare).toHaveBeenCalledTimes(1); expect(m.update.mock.calls.at(-1)?.[0].data).toMatchObject({ status: "FAILED" }); });
it.each(["image", "provider", "malformed", "changed"])("does not treat %s failure as passing evidence", async kind => { if (kind === "image") m.image.mockRejectedValue(new Error("secret")); if (kind === "provider") m.compare.mockRejectedValue(new Error("secret")); if (kind === "malformed") m.compare.mockResolvedValue({ assessment: "pass", summary: "bad", issues: [], confidence: 1, extra: true }); if (kind === "changed") candidate.sourceFingerprint = "stale"; if (kind === "malformed") candidate.result = { observations: [{ mediaId: "unknown" }], totalPhotos: 2 }; await processPhotoReviewQueue(); expect(m.update.mock.calls.at(-1)?.[0].data.status).toBe("FAILED"); expect(JSON.stringify(m.update.mock.calls)).not.toContain("secret"); });
it("fingerprint tracks references, visibility context and laundry readiness", () => { const first = photoSourceFingerprint(submission); submission.laundryReady = false; expect(photoSourceFingerprint(submission)).not.toBe(first); submission.laundryReady = true; submission.data.__templateSchema.sections[0].fields[0].references[0].storageKey += "changed"; expect(photoSourceFingerprint(submission)).not.toBe(first); });
it("no uploaded reference stays skipped, never pass", async () => { submission.data.__templateSchema.sections[0].fields[0].references = []; await processPhotoReviewQueue(); expect(m.compare).not.toHaveBeenCalled(); expect(m.update.mock.calls[2][0].data.result.observations[0].assessment).toBe("skipped"); });
it("rejects duplicate or contradictory observations and caps deductions per field", () => { const finding = { id: "f", mediaId: "photo", fieldId: "bath", fieldLabel: "Bath", description: "Mess", severity: "major" as const, confidence: .9 }; const observation = { mediaId: "photo", fieldId: "bath", fieldLabel: "Bath", assessment: "issue", summary: "Mess", findings: [finding] }; expect(() => parsePhotoReviewResult({ totalPhotos: 2, observations: [observation, observation] })).toThrow(); expect(() => parsePhotoReviewResult({ totalPhotos: 1, observations: [{ ...observation, assessment: "pass" }] })).toThrow(); expect(proposedPhotoDeduction([finding, { ...finding, id: "g" }], ["f", "g"], .8, 10)).toBe(5); expect(proposedPhotoDeduction([finding], ["f"], .95, 10)).toBe(0); });
