import { describe, it, expect } from "vitest";
import { careCatalog, careDue, dueDay, suitableCareJob, careCoverage, type CareAsset } from "@/lib/property-care/policy";
const asset: CareAsset = { id: "10000000-0000-4000-8000-000000000000", catalogId: "curtains", location: "Bedroom", applicability: "APPLICABLE", enabled: true, safeAccess: true, productsReady: true, inspectionDays: 7, cleaningDays: 30, inspectionMinutes: 1, cleaningMinutes: 5, firstCleaningDue: null, cleaningNeeded: false, manualUrl: "", product: "Approved", reason: "Reviewed" };
it("retains all 49 catalog recommendations without auto-enabling routine additions", () => { expect(careCatalog).toHaveLength(49); expect(careCatalog.find(x => x.id === "plants")?.cleaning.kind).toBe("condition_only"); });
it("unknown baseline needs inspection, not fabricated overdue cleaning", () => { expect(careDue(asset, { inspectedAt: null, cleanedAt: null }, "Australia/Sydney")).toEqual({ INSPECT: "INITIAL_INSPECTION", CLEAN: null }); });
it("inspection and cleaning use independent local calendar clocks across DST", () => { expect(dueDay("2026-10-03T14:30:00Z", 1, "Australia/Sydney")).toBe("2026-10-05"); expect(careDue(asset, { inspectedAt: "2026-10-04T00:00:00Z", cleanedAt: "2026-09-01T00:00:00Z" }, "Australia/Sydney")).toEqual({ INSPECT: "2026-10-11", CLEAN: "2026-10-01" }); });
it("completed cleaning clears a condition cycle and does not reuse first due without recurrence", () => { expect(careDue({ ...asset, cleaningDays: null, firstCleaningDue: "2026-10-03", cleaningNeeded: true, conditionSince: "2026-10-03T00:00:00Z" }, { inspectedAt: null, cleanedAt: "2026-10-04T00:00:00Z" }, "Australia/Sydney").CLEAN).toBeNull(); });
describe("booked time eligibility", () => {
 const job = { id: "j", jobType: "AIRBNB_TURNOVER", status: "ASSIGNED", scheduledDate: new Date("2026-10-06"), startTime: "09:00", endTime: "11:00", estimatedHours: 2 };
 const budget = { jobId: "j", minutes: 20, normalMinutes: 90, ready: true, reason: "Approved" };
 const fits = (j = job, b: any = budget, used = 0) => suitableCareJob(j, b, 10, used, "2026-10-05", new Date("2026-10-04"), "Australia/Sydney");
 it("requires budget, readiness, time window, eligible status and remaining paid minutes", () => { expect(fits()).toBe(true); expect(fits({ ...job, jobType: "GUTTER_CLEANING" })).toBe(false); expect(fits(job, undefined)).toBe(true); expect(fits(job, null)).toBe(false); expect(fits(job, { ...budget, ready: false })).toBe(false); expect(fits(job, budget, 15)).toBe(false); expect(fits({ ...job, status: "COMPLETED" })).toBe(false); expect(fits({ ...job, estimatedHours: 1 })).toBe(false); expect(fits({ ...job, startTime: "" })).toBe(false); });
});
it("coverage names possible matches without replacing custom P11 fields", () => { const schema = { sections: [{ fields: [{ id: "P11-curtain", label: "Curtains custom exception" }, { id: "curtains2", label: "Curtains extra" }] }] }; const original = JSON.stringify(schema); expect(careCoverage(schema, []).find(x => x.id === "curtains")?.status).toBe("POSSIBLE_DUPLICATE_REVIEW"); expect(careCoverage(schema, []).find(x => x.id === "stove")?.status).toBe("ROUTINE_PROPOSAL_REQUIRED"); expect(JSON.stringify(schema)).toBe(original); });
