// @vitest-environment node
import { beforeEach, expect, it, vi } from "vitest";
const m = vi.hoisted(() => ({ execute: vi.fn(), query: vi.fn(), receipt: vi.fn(), update: vi.fn(), find: vi.fn(), item: vi.fn(), create: vi.fn(), audit: vi.fn() }));
vi.mock("@/lib/db", () => ({ db: { $transaction: (fn: any) => fn({ $executeRaw: m.execute, $queryRaw: m.query, heldStock: { findUnique: m.find, create: m.create, update: m.update }, inventoryItem: { findFirst: m.item }, auditLog: { create: m.audit, findUnique: m.receipt } }) } }));
import { recordOwnHeldStock, adjustOwnHeldStock } from "@/lib/inventory/self-held-stock";
const input = { requestId: "138293ca-452d-4de7-b9cb-54b6c54a6c99", itemId: "soap", quantity: 3, sourceNote: "Already in my car" };
beforeEach(() => { vi.resetAllMocks(); m.find.mockResolvedValue(null); m.item.mockResolvedValue({ id: "soap" }); });
it("records owner and audit atomically without property stock mutation", async () => { const saved = await recordOwnHeldStock("cleaner-a", input); expect(m.execute.mock.invocationCallOrder[0]).toBeLessThan(m.find.mock.invocationCallOrder[0]); expect(m.create).toHaveBeenCalledWith({ data: expect.objectContaining({ id: saved.id, holderUserId: "cleaner-a", quantity: 3, originalQty: 3 }) }); expect(m.audit).toHaveBeenCalledWith({ data: expect.objectContaining({ userId: "cleaner-a", entityId: saved.id }) }); });
it("replays the same request even after some stock was delivered", async () => { m.find.mockResolvedValue({ holderUserId: "cleaner-a", itemId: "soap", originalQty: 3, quantity: 1, sourceNote: input.sourceNote }); expect((await recordOwnHeldStock("cleaner-a", input)).duplicated).toBe(true); expect(m.create).not.toHaveBeenCalled(); expect(m.audit).not.toHaveBeenCalled(); });
it("rejects a reused request with changed quantity", async () => { m.find.mockResolvedValue({ holderUserId: "cleaner-a", itemId: "soap", originalQty: 2, sourceNote: input.sourceNote }); await expect(recordOwnHeldStock("cleaner-a", input)).rejects.toMatchObject({ status: 409 }); expect(m.create).not.toHaveBeenCalled(); });
it("isolates the same request ID between holders and records real actor", async () => { const a = await recordOwnHeldStock("a", input); const b = await recordOwnHeldStock("b", input, "admin"); expect(a.id).not.toBe(b.id); expect(m.audit.mock.calls[1][0].data).toMatchObject({ userId: "admin", after: { holderUserId: "b" } }); });
it("rejects inactive items and caller-selected owners", async () => { m.item.mockResolvedValue(null); await expect(recordOwnHeldStock("a", input)).rejects.toMatchObject({ status: 409 }); await expect(recordOwnHeldStock("a", { ...input, holderUserId: "b" })).rejects.toThrow(); expect(m.create).not.toHaveBeenCalled(); });
it.each([0, -1, Infinity, 1_000_001])("rejects invalid quantity %s", async quantity => { await expect(recordOwnHeldStock("a", { ...input, quantity })).rejects.toThrow(); expect(m.execute).not.toHaveBeenCalled(); });
const adjustment = { requestId: input.requestId, heldStockId: "held-a", expectedUpdatedAt: "2026-09-22T01:00:00.000Z", quantity: 0, reason: "Used up while cleaning" };
it("locks and audits a zero remaining correction without claiming delivery", async () => { m.find.mockResolvedValue({ id: "held-a", holderUserId: "a", status: "HELD", quantity: 3, updatedAt: new Date(adjustment.expectedUpdatedAt) }); await adjustOwnHeldStock("a", adjustment); expect(m.query.mock.invocationCallOrder[0]).toBeLessThan(m.find.mock.invocationCallOrder[0]); expect(m.update).toHaveBeenCalledWith({ where: { id: "held-a" }, data: { quantity: 0 } }); expect(m.audit.mock.calls[0][0].data).toMatchObject({ before: { quantity: 3 }, after: { quantity: 0, reason: adjustment.reason } }); });
it("rejects another holder and stale delivery version", async () => { m.find.mockResolvedValue({ holderUserId: "b" }); await expect(adjustOwnHeldStock("a", adjustment)).rejects.toMatchObject({ status: 404 }); m.find.mockResolvedValue({ holderUserId: "a", status: "HELD", updatedAt: new Date("2026-09-22T02:00:00.000Z") }); await expect(adjustOwnHeldStock("a", adjustment)).rejects.toMatchObject({ status: 409 }); expect(m.update).not.toHaveBeenCalled(); });
it("replays an adjustment receipt without resetting a later delivery", async () => { m.receipt.mockResolvedValue({ after: { holderUserId: "a", heldStockId: adjustment.heldStockId, expectedUpdatedAt: adjustment.expectedUpdatedAt, quantity: 0, reason: adjustment.reason } }); expect((await adjustOwnHeldStock("a", adjustment)).duplicated).toBe(true); expect(m.update).not.toHaveBeenCalled(); await expect(adjustOwnHeldStock("a", { ...adjustment, quantity: 2 })).rejects.toMatchObject({ status: 409 }); });
