import type { EstimationTemplate } from "./types";

export const AREA_FALLBACK_BY_PROPERTY: Record<string, number> = {
  STUDIO: 35,
  APARTMENT: 70,
  UNIT: 80,
  TOWNHOUSE: 120,
  DUPLEX: 150,
  HOUSE: 180,
};

export const DEFAULT_TEMPLATES: EstimationTemplate[] = [
  {
    id: "airbnb-turnover",
    name: "Airbnb Turnover",
    appliesTo: ["AIRBNB_TURNOVER"],
    baseHours: 2.5,
    hoursPerBedroom: 0.5,
    hoursPerBathroom: 0.75,
    hoursPerFloor: 0.25,
    hoursPerBalcony: 0.25,
    hoursPerAppliance: 0.25,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 55,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 80, cleaners: 1 },
      { minSqm: 80, maxSqm: 150, cleaners: 2 },
      { minSqm: 150, maxSqm: 250, cleaners: 2 },
      { minSqm: 250, maxSqm: 400, cleaners: 3 },
      { minSqm: 400, cleaners: 4 },
    ],
  },
  {
    id: "deep-clean",
    name: "Deep Clean",
    appliesTo: ["DEEP_CLEAN"],
    baseHours: 4,
    hoursPerBedroom: 0.75,
    hoursPerBathroom: 1,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0.5,
    hoursPerAppliance: 0.5,
    hoursPerSpecialRequest: 0.75,
    hourlyRate: 65,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 80, cleaners: 1 },
      { minSqm: 80, maxSqm: 150, cleaners: 2 },
      { minSqm: 150, maxSqm: 250, cleaners: 2 },
      { minSqm: 250, maxSqm: 400, cleaners: 3 },
      { minSqm: 400, cleaners: 4 },
    ],
  },
  {
    id: "end-of-lease",
    name: "End of Lease",
    appliesTo: ["END_OF_LEASE"],
    baseHours: 5,
    hoursPerBedroom: 0.75,
    hoursPerBathroom: 1,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0.5,
    hoursPerAppliance: 0.5,
    hoursPerSpecialRequest: 0.75,
    hourlyRate: 60,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 80, cleaners: 1 },
      { minSqm: 80, maxSqm: 150, cleaners: 2 },
      { minSqm: 150, maxSqm: 250, cleaners: 2 },
      { minSqm: 250, maxSqm: 400, cleaners: 3 },
      { minSqm: 400, cleaners: 4 },
    ],
  },
  {
    id: "general-clean",
    name: "General Clean",
    appliesTo: ["GENERAL_CLEAN"],
    baseHours: 3,
    hoursPerBedroom: 0.5,
    hoursPerBathroom: 0.5,
    hoursPerFloor: 0.25,
    hoursPerBalcony: 0.25,
    hoursPerAppliance: 0.25,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 50,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 100, cleaners: 1 },
      { minSqm: 100, maxSqm: 200, cleaners: 2 },
      { minSqm: 200, maxSqm: 350, cleaners: 2 },
      { minSqm: 350, cleaners: 3 },
    ],
  },
  {
    id: "post-construction",
    name: "Post Construction",
    appliesTo: ["POST_CONSTRUCTION"],
    baseHours: 6,
    hoursPerBedroom: 1,
    hoursPerBathroom: 1.25,
    hoursPerFloor: 0.75,
    hoursPerBalcony: 0.5,
    hoursPerAppliance: 0.5,
    hoursPerSpecialRequest: 1,
    hourlyRate: 70,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 100, cleaners: 2 },
      { minSqm: 100, maxSqm: 200, cleaners: 2 },
      { minSqm: 200, maxSqm: 350, cleaners: 3 },
      { minSqm: 350, cleaners: 4 },
    ],
  },
  {
    id: "pressure-wash",
    name: "Pressure Wash",
    appliesTo: ["PRESSURE_WASH"],
    baseHours: 3,
    hoursPerBedroom: 0,
    hoursPerBathroom: 0,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0.5,
    hoursPerAppliance: 0,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 60,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 150, cleaners: 1 },
      { minSqm: 150, maxSqm: 300, cleaners: 2 },
      { minSqm: 300, cleaners: 3 },
    ],
  },
  {
    id: "window-clean",
    name: "Window Clean",
    appliesTo: ["WINDOW_CLEAN"],
    baseHours: 2,
    hoursPerBedroom: 0.25,
    hoursPerBathroom: 0.25,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0.25,
    hoursPerAppliance: 0,
    hoursPerSpecialRequest: 0.25,
    hourlyRate: 55,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 150, cleaners: 1 },
      { minSqm: 150, maxSqm: 300, cleaners: 2 },
      { minSqm: 300, cleaners: 3 },
    ],
  },
  {
    id: "lawn-mowing",
    name: "Lawn Mowing",
    appliesTo: ["LAWN_MOWING"],
    baseHours: 1.5,
    hoursPerBedroom: 0,
    hoursPerBathroom: 0,
    hoursPerFloor: 0,
    hoursPerBalcony: 0,
    hoursPerAppliance: 0,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 45,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 200, cleaners: 1 },
      { minSqm: 200, maxSqm: 500, cleaners: 2 },
      { minSqm: 500, cleaners: 3 },
    ],
  },
  {
    id: "carpet-steam",
    name: "Carpet Steam Clean",
    appliesTo: ["CARPET_STEAM_CLEAN"],
    baseHours: 3,
    hoursPerBedroom: 0.5,
    hoursPerBathroom: 0,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0,
    hoursPerAppliance: 0,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 60,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 100, cleaners: 1 },
      { minSqm: 100, maxSqm: 250, cleaners: 2 },
      { minSqm: 250, cleaners: 3 },
    ],
  },
  {
    id: "mold-treatment",
    name: "Mold Treatment",
    appliesTo: ["MOLD_TREATMENT"],
    baseHours: 4,
    hoursPerBedroom: 0.75,
    hoursPerBathroom: 1,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0,
    hoursPerAppliance: 0.25,
    hoursPerSpecialRequest: 1,
    hourlyRate: 75,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 80, cleaners: 1 },
      { minSqm: 80, maxSqm: 150, cleaners: 2 },
      { minSqm: 150, cleaners: 3 },
    ],
  },
  {
    id: "commercial-recurring",
    name: "Commercial Recurring",
    appliesTo: ["COMMERCIAL_RECURRING"],
    baseHours: 4,
    hoursPerBedroom: 0,
    hoursPerBathroom: 0.75,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0,
    hoursPerAppliance: 0.25,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 55,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 100, cleaners: 1 },
      { minSqm: 100, maxSqm: 250, cleaners: 2 },
      { minSqm: 250, maxSqm: 500, cleaners: 3 },
      { minSqm: 500, cleaners: 4 },
    ],
  },
  {
    id: "upholstery",
    name: "Upholstery Cleaning",
    appliesTo: ["UPHOLSTERY_CLEANING"],
    baseHours: 2,
    hoursPerBedroom: 0.25,
    hoursPerBathroom: 0,
    hoursPerFloor: 0,
    hoursPerBalcony: 0,
    hoursPerAppliance: 0,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 55,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 150, cleaners: 1 },
      { minSqm: 150, cleaners: 2 },
    ],
  },
  {
    id: "tile-grout",
    name: "Tile Grout Cleaning",
    appliesTo: ["TILE_GROUT_CLEANING"],
    baseHours: 3,
    hoursPerBedroom: 0.25,
    hoursPerBathroom: 0.75,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0.25,
    hoursPerAppliance: 0,
    hoursPerSpecialRequest: 0.75,
    hourlyRate: 60,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 100, cleaners: 1 },
      { minSqm: 100, maxSqm: 200, cleaners: 2 },
      { minSqm: 200, cleaners: 3 },
    ],
  },
  {
    id: "gutter",
    name: "Gutter Cleaning",
    appliesTo: ["GUTTER_CLEANING"],
    baseHours: 2,
    hoursPerBedroom: 0,
    hoursPerBathroom: 0,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0,
    hoursPerAppliance: 0,
    hoursPerSpecialRequest: 0.5,
    hourlyRate: 60,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 150, cleaners: 1 },
      { minSqm: 150, maxSqm: 300, cleaners: 2 },
      { minSqm: 300, cleaners: 3 },
    ],
  },
  {
    id: "spring-cleaning",
    name: "Spring Cleaning",
    appliesTo: ["SPRING_CLEANING"],
    baseHours: 4,
    hoursPerBedroom: 0.75,
    hoursPerBathroom: 0.75,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0.5,
    hoursPerAppliance: 0.25,
    hoursPerSpecialRequest: 0.75,
    hourlyRate: 55,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 100, cleaners: 1 },
      { minSqm: 100, maxSqm: 200, cleaners: 2 },
      { minSqm: 200, maxSqm: 350, cleaners: 2 },
      { minSqm: 350, cleaners: 3 },
    ],
  },
  {
    id: "special-clean",
    name: "Special Clean",
    appliesTo: ["SPECIAL_CLEAN"],
    baseHours: 3,
    hoursPerBedroom: 0.5,
    hoursPerBathroom: 0.75,
    hoursPerFloor: 0.5,
    hoursPerBalcony: 0.25,
    hoursPerAppliance: 0.5,
    hoursPerSpecialRequest: 0.75,
    hourlyRate: 60,
    minCleanersForSqm: [
      { minSqm: 0, maxSqm: 100, cleaners: 1 },
      { minSqm: 100, maxSqm: 200, cleaners: 2 },
      { minSqm: 200, cleaners: 3 },
    ],
  },
];

export const HEAVY_JOB_TYPES = ["DEEP_CLEAN", "POST_CONSTRUCTION", "END_OF_LEASE", "MOLD_TREATMENT"];

export const CONDITION_MULTIPLIER: Record<string, number> = {
  light: 0.85,
  standard: 1,
  heavy: 1.3,
};
