"use strict";(()=>{var e={};e.id=42644,e.ids=[42644],e.modules={53524:e=>{e.exports=require("@prisma/client")},72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},58545:e=>{e.exports=require("pino")},27790:e=>{e.exports=require("assert")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},17702:e=>{e.exports=require("events")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},19801:e=>{e.exports=require("os")},68621:e=>{e.exports=require("punycode")},86624:e=>{e.exports=require("querystring")},76162:e=>{e.exports=require("stream")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},71568:e=>{e.exports=require("zlib")},93977:e=>{e.exports=require("node:fs/promises")},18052:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>E,patchFetch:()=>w,requestAsyncStorage:()=>f,routeModule:()=>y,serverHooks:()=>_,staticGenerationAsyncStorage:()=>S});var s={};r.r(s),r.d(s,{GET:()=>g,dynamic:()=>M,runtime:()=>x});var a=r(49303),n=r(88716),o=r(60670),i=r(87070),u=r(75571),c=r(53524),l=r(19801),p=r(93977),d=r(5018),m=r(9487);let x="nodejs",M="force-dynamic";async function h(){if("linux"!==(0,l.platform)())return null;try{let e=async()=>{let e=(await (0,p.readFile)("/proc/stat","utf8")).split("\n")[0].trim().split(/\s+/).slice(1).map(Number),t=e[7]??0,r=e.reduce((e,t)=>e+t,0);return{steal:t,total:r}},t=await e();await new Promise(e=>setTimeout(e,500));let r=await e(),s=r.total-t.total,a=r.steal-t.steal;if(s<=0)return null;return a/s*100}catch{return null}}let q=globalThis;async function g(){let e=await (0,u.getServerSession)(d.L);if(e?.user?.role!==c.Role.ADMIN)return i.NextResponse.json({error:"Forbidden"},{status:403});let t=h(),r=process.memoryUsage(),s=process.uptime(),a=process.cpuUsage();await new Promise(e=>setTimeout(e,1e3));let n=process.cpuUsage(a),o=(n.user+n.system)/1e6*100,p=q.__sneekSseLiveLocations?.active??0,x=(q.__sneekWorkerFailures??[]).slice(-20).reverse(),M=q.__sneekJobRuns??[],g=Date.now()-36e5,y=M.filter(e=>e.finishedAt>g),f={};for(let e of y){let t=f[e.name]??={count:0,totalMs:0,failures:0,maxMs:0};t.count+=1,t.totalMs+=e.durationMs,e.ok||(t.failures+=1),e.durationMs>t.maxMs&&(t.maxMs=e.durationMs)}let S=Object.entries(f).map(([e,t])=>({name:e,count:t.count,totalMs:t.totalMs,maxMs:t.maxMs,failures:t.failures,percentOfHour:Math.round(t.totalMs/36e5*1e3)/10})).sort((e,t)=>t.totalMs-e.totalMs),_=await m.db.$queryRawUnsafe(`SELECT pid, usename, state, query_start,
              EXTRACT(EPOCH FROM (NOW() - query_start))::int AS seconds,
              LEFT(query, 200) AS query
       FROM pg_stat_activity
       WHERE state != 'idle' AND datname = current_database()
       ORDER BY query_start NULLS LAST
       LIMIT 30`).catch(()=>[]),E=await m.db.$queryRawUnsafe(`SELECT state, COUNT(*)::int AS count
       FROM pgboss.job
       GROUP BY state`).catch(()=>[]),w=await m.db.$queryRawUnsafe(`SELECT LEFT(query, 200) AS query,
              calls::int AS calls,
              total_exec_time::int AS total_ms,
              mean_exec_time::int AS mean_ms
       FROM pg_stat_statements
       ORDER BY total_exec_time DESC
       LIMIT 10`).catch(()=>[]),v=await m.db.$queryRawUnsafe("SELECT name, cron, updated_on FROM pgboss.schedule ORDER BY name").catch(()=>[]),R=await m.db.notification.count({where:{channel:"EMAIL",status:"SENT",sentAt:{gte:new Date(Date.now()-864e5)}}}).catch(()=>null),A=q.__sneekWebSchedulerLastTick??null,b={resendConfigured:!!(process.env.RESEND_API_KEY&&process.env.RESEND_API_KEY.trim()),scheduleCount:v.length,schedules:v.map(e=>({name:e.name,cron:e.cron,updatedOn:e.updated_on})),emailsSentLast24h:R,webFallbackLastTickAt:A?new Date(A).toISOString():null},T=await t,O=(0,l.cpus)().length,L=(0,l.loadavg)(),P={platform:(0,l.platform)(),cpuCount:O,loadAvg1m:L[0],loadAvg5m:L[1],loadAvg15m:L[2],totalMemMB:Math.round((0,l.totalmem)()/1024/1024),freeMemMB:Math.round((0,l.freemem)()/1024/1024),cpuStealPercent:T};return i.NextResponse.json({capturedAt:new Date().toISOString(),os:P,process:{pid:process.pid,uptimeSeconds:Math.round(s),cpuPercent:Math.round(10*o)/10,memory:{rssMB:Math.round(r.rss/1024/1024),heapUsedMB:Math.round(r.heapUsed/1024/1024),heapTotalMB:Math.round(r.heapTotal/1024/1024),externalMB:Math.round(r.external/1024/1024)},nodeVersion:process.version,platform:process.platform},sse:{liveLocationsActive:p},workers:{recentFailures:x,jobStats:S,runsObserved:M.length},scheduler:b,db:{activeQueries:_.map(e=>({pid:e.pid,user:e.usename,state:e.state,seconds:e.seconds??0,query:e.query??""})),jobsByState:E,slowQueries:w}})}let y=new a.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/admin/system/diagnostics/route",pathname:"/api/admin/system/diagnostics",filename:"route",bundlePath:"app/api/admin/system/diagnostics/route"},resolvedPagePath:"E:\\sNeek Property Service\\Website\\app\\api\\admin\\system\\diagnostics\\route.ts",nextConfigOutput:"",userland:s}),{requestAsyncStorage:f,staticGenerationAsyncStorage:S,serverHooks:_}=y,E="/api/admin/system/diagnostics/route";function w(){return(0,o.patchFetch)({serverHooks:_,staticGenerationAsyncStorage:S})}}};var t=require("../../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[38948,51251,83714,79430,20330,3643,55972,99756,5018],()=>r(18052));module.exports=s})();